[build]
  command = "GENERATE_SOURCEMAP=true CI=true npm run build"
  publish = "build"
  [build.environment]
    NODE_ENV = "production"
    NPM_FLAGS = "--verbose"
    DEBUG = "*"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self' https://idonotwritecode.com; img-src 'self' blob: data: https://idonotwritecode.com; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline';"